#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: udphop
# REQUIRE: LOGIN DAEMON
# KEYWORD: shutdown

# Add these lines to /etc/rc.conf.local or /etc/rc.conf to enable `udphop':
#
# udphop_enable (bool):           Set to "NO" by default.
#                                 Set it to "YES" to enable udphop
# udphop_config (path):           Set to "/usr/local/etc/udphop/config.conf" by default
#                                 Set it to the udphop server config

. /etc/rc.subr

name="udphop"
rcvar="${name}_enable"

eval ": \${${name}_enable:=\"NO\"}"
eval ": \${${name}_config:=\"/usr/local/etc/${name}/config.conf\"}"

pidfile="/var/run/${name}.pid"
procname="/usr/local/bin/udphop"
configfile="$(eval echo \${${name}_config})"

start_precmd="udphop_startprecmd"
start_cmd=udphop_start

udphop_startprecmd()
{
	touch "${pidfile}"
}

udphop_start()
{
	/usr/sbin/daemon -c -p ${pidfile} ${procname} ${configfile} > /dev/null 2>&1
}

load_rc_config "$name"
run_rc_command "$1"
